@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package plus.dragons.createminingindustry.contraptions.mining.blazeminer.product;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;