modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId="create_echo_mining"
version="${file.jarVersion}"
displayName="Create Echo Mining"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="todo.png" #optional
credits="TODO" #optional
authors="TODO" #optional
description='''
TODO
'''
[[dependencies.create_echo_mining]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_echo_mining]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_echo_mining]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0.i,)"
    ordering="NONE"
    side="BOTH"
